name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.x", "3.6"]
    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: make install
      - name: Install dev dependencies
        run: make dev-install
      - name: Lint with flake8
        run: make lint
      - name: Run tests.
        # For now, integration tests are limited to SQLite and not MySQL etc.,
        # so can run on Github.
        run: make test
