name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.x"]
    name: Python ${{ matrix.python }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: make install
      - name: Install dev dependencies
        run: make dev-install
      - name: Lint with flake8
        run: make lint
      - name: Lint PY 2/3 compatibility
        run: make lint3
      - name: Unit and integration tests.
        # For now, integration tests are limited to SQLite, so can run on
        # Github.
        run: make test
